image: hugomods/hugo:exts-0.153.0

variables:
  GIT_DEPTH: "0"
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production
  TZ: Asia/Kolkata

pages:
  stage: deploy
  script:
    - hugo version
    - hugo --minify --gc --baseURL "${CI_PAGES_URL}/"
  artifacts:
    paths:
      - public
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: production
    url: $CI_PAGES_URL
