baseURL = "https://example.com"
languageCode = "en-us"
title = "My Portfolio Console"
disableKinds = ["taxonomy", "term"]

[params]
  owner = "Your Name"
  role = "Sr. Cloud Full Stack Developer"
  region = "Delhi NCR"
