baseURL = "/"
languageCode = "en-us"
title = "My Portfolio Console"
disableKinds = ["taxonomy", "term"]
relativeURLs = true
canonifyURLs = false

[params]
  owner = "Your Name"
  role = "Sr. Cloud Full Stack Developer"
  region = "Delhi NCR"
